---
title: "Home"
author: "Adrien Boukobza"
date: "2 mars 2019"
output: html_document
---

## Home

The recent raise of STD in the USA is a very hot topic because it could represent a major public health issue within few years. That's why we decided to examine the data about this subject.

First, to have a global overview of the importance of STD in the USA we chose to make a map showing the density of STD in each state on 1000 inhabitants.

The second point, is a simple computed prevision to see how the number of cases should 
evolve in few years in each state and for each disease

**CAUTION**: These results are only mathematical previsions of the cases, and don't have a real predictive value.

The third point allows the user to compare the chances to have a specific disease for a specific population in each state, comparing with another one with a different parameter.

*Risk ratio* is the probability of the outcome of an event in an exposed group compared to a non exposed one.

*Odds Ratio* is quite based on the Risk ratio but also uses the inverse probability of an event to calculate a value.

Finally, the user can consult the data and copy it for his own study.
